# Generated by Django 5.1.4 on 2024-12-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_habit_last_completed_habit_streak_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='duration',
            field=models.IntegerField(choices=[(7, 'One week'), (14, 'Two weeks'), (30, 'A month'), (90, 'Three months'), (180, 'Six months')], default=7),
        ),
    ]
