# Generated by Django 5.1.4 on 2024-12-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0004_achievement_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpeg', null=True, upload_to='profile_pictures/'),
        ),
    ]
