# Generated by Django 5.1.4 on 2024-12-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0005_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_bio',
            field=models.TextField(blank=True, default='No bio yet', max_length=200, null=True),
        ),
    ]
