# Generated by Django 5.1.4 on 2024-12-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0006_customuser_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='relapse_dates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
