# Generated by Django 5.1.4 on 2025-01-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0008_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='last_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
