# Generated by Django 5.1.4 on 2025-01-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0013_notification_friend_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('point', models.IntegerField()),
                ('ended', models.BooleanField(default=False)),
                ('answers', models.JSONField()),
            ],
        ),
    ]
