# Generated by Django 5.1.4 on 2025-01-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0016_userchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
