# Generated by Django 5.1.4 on 2025-01-28 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0019_habit_latest_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relapse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relapses', to='habit_tracker.habit')),
            ],
        ),
    ]
